---
title: "MERDs Data Analyses"
author: "Tayler Ulbrich and Lukas Bell-Dereske"
date: "9/27/2021"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# Load Files 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(car)
library(emmeans)
library(dplyr)
library(MASS)
library(knitr)
options(contrasts=c("contr.sum", "contr.poly"))

germ.md <- read.csv("D:/MERDS_2018/merds/Switchgrass/R_data/MERDS_GerminationExperiment_metadata.csv", header = TRUE)

germ.raw <- read.csv("D:/MERDS_2018/merds/Switchgrass/R_data/MERDS_GerminationExperiment_RawData.csv", header = TRUE)

germdata <- merge(germ.md, germ.raw, by = "ID")
dim(germdata)




```


# Day 11 Germination 
## PLOT
```{r}


germdata_Day11_sum=germdata %>% group_by(Soil_Treatment,Nitrogen_Treatment) %>% 
  summarise(mean=mean(Day11),n=n(),se=sd(Day11)/sqrt(n()))

(germination_Day11_p=ggplot(germdata)+
    geom_errorbar(data = germdata_Day11_sum,aes(group=factor(Nitrogen_Treatment,levels = c("Low","High")),
                                                  x=factor(Soil_Treatment, levels = c("Sterile","Live")),y=mean,ymin=mean-se,ymax=mean+se),
                width=.3,size=1, position = position_dodge(0.5), color="black")+
  geom_point(aes(x=factor(Soil_Treatment, levels = c("Sterile","Live")),y=Day11,
                 shape=factor(Nitrogen_Treatment,levels = c("Low","High")),
                 group=factor(Nitrogen_Treatment,levels = c("Low","High"))), size=3, position = position_dodge(0.5),alpha=0.5,fill="white")+
  geom_point(data = germdata_Day11_sum,aes(x=factor(Soil_Treatment, levels = c("Sterile","Live")),y=mean, 
                                               shape=factor(Nitrogen_Treatment,levels = c("Low","High")),
                                          group=factor(Nitrogen_Treatment,levels = c("Low","High"))), 
             size=7, position = position_dodge(0.5),stroke=1.5,fill="white")+
  scale_y_continuous(name ="Germination per Petri dish\n(# of germinants)")+
  scale_x_discrete(label=c("Sterile","Live"))+
  scale_shape_manual(values= c(25,15),name="Nitrogen")+
  theme_bw(base_size = 24)+theme(axis.text = element_text(size = 30),axis.title.x = element_blank(), axis.title.y = element_text(size = 36),
                   panel.grid.major = element_blank(), panel.grid.minor = element_blank(),legend.key.height = unit(1,"cm")))

#ggsave("D:/MERDS_2018/merds/Switchgrass/R_fig/Nit_germination_day11_dot_error.png",germination_Day11_p,width =12,height = 8,device="png")
#ggsave("D:/MERDS_2018/merds/Switchgrass/R_fig/Nit_germination_day11_dot_error.svg",germination_Day11_p,width =12,height = 8,device="svg")
```
## Stats
```{r}


# test for normal residuals and equal variances (ANOVA assumptions)


# check normal residuals
qqPlot(germdata$Day11)
hist(germdata$Day11)
lm.GermDay11 = lm(Day11 ~ Soil_Treatment*Nitrogen_Treatment, data = germdata)
#Nitrogen_Treatment                  21.02  1   8.8942  0.005108 ** 
# shapiro test - null hypothesis: residuals are normally distributed 
hist(stdres(lm.GermDay11))
shapiro.test(stdres(lm.GermDay11)) 
plot(lm.GermDay11)

# ANOVA 
Anova(lm.GermDay11, type = "III")

# tukeys comparison 
emmeans(lm.GermDay11, pairwise~Nitrogen_Treatment|Soil_Treatment)


```
Formatted Anova table
```{r echo=FALSE, results='asis'}
anova_lm.GermDay11=Anova(lm.GermDay11, type = "III")
df_anova_lm.GermDay11=data.frame(row.names =row.names(anova_lm.GermDay11),"Df"=anova_lm.GermDay11$Df,"F-value"=anova_lm.GermDay11$`F value`,"P-value"=anova_lm.GermDay11$`Pr(>F)`)
kable(df_anova_lm.GermDay11,align = "c",digits = c(1,2,3), caption= "Germination at day 3")
```

#### Percentage Difference and magnitude High versus low nitrogen
```{r echo=FALSE}
#Mean germination across treatments
germdata %>%  summarise_at("Day11", list(~n(),~mean(.),~sd(.),se=~sd(.)/sqrt(n())))

germdata_N_level=germdata %>% group_by(Nitrogen_Treatment)%>% summarise_at("Day11", list(~n(),~mean(.),~sd(.),se=~sd(.)/sqrt(n())))

#Percentage Difference
((germdata_N_level[germdata_N_level$Nitrogen_Treatment=="High",]$mean-germdata_N_level[germdata_N_level$Nitrogen_Treatment=="Low",]$mean)/germdata_N_level[germdata_N_level$Nitrogen_Treatment=="Low",]$mean)*100


germdata_N_level[germdata_N_level$Nitrogen_Treatment=="High",]$mean-germdata_N_level[germdata_N_level$Nitrogen_Treatment=="Low",]$mean

```



## Does location in the growth chamber affect the germination
```{r}
head(germdata)

ggplot(germdata,aes(x=Shelf,y=Day11, color=factor(Row),group=interaction(Shelf,Row)))+geom_boxplot()
ggplot(germdata,aes(x=Shelf,y=Day11, color=factor(Row),group=interaction(Shelf,Column)))+geom_boxplot()
ggplot(germdata,aes(x=Row,y=Day11, color=factor(Row),group=interaction(Row,Column)))+geom_boxplot()
ggplot(germdata,aes(x=Column,y=Day11, color=factor(Row),group=interaction(Column,Row)))+geom_boxplot()


qqPlot(germdata$Day11)
hist(germdata$Day11)
lm.GermDay11_pos = lm(Day11 ~ factor(Row)+factor(Column)+Shelf,data = germdata)
qqPlot(stdres(lm.GermDay11_pos))
hist(stdres(lm.GermDay11_pos))
shapiro.test(stdres(lm.GermDay11_pos)) 
#plot(lm.GermDay11_pos)

# ANOVA 
Anova(lm.GermDay11_pos, type = "III")

```

